### ISSUE TITLE
Python on ESP32 installation

### ISSUE THREAD

**Issue by SouperMan3** [UDOOboard/Key-Docs#3]
Please provide instruc.tions on how to install micropython on the ESP32 for Udoo Key.   See comment in forum.

**Comment by dima91** [comment]
Hi, sorry for the late answer!

If you didn't find a solution, I  tested just now the procedure below:

1. Go to ESP32 MicroPython page and download the firmware binary file. I downloaded [v1.21.0 (2023-10-05) .bin](https://micropython.org/resources/firmware/ESP32_GENERIC-20231005-v1.21.0.bin) in `Firmware`/`Releases` section;

2. With [esptool.py](https://github.com/espressif/esptool) program installed, erase the microcontroller flash with command below:
`esptool.py --chip esp32 --port <port> erase_flash`
changing `<port>` with the current serial port;

3. Install the MicroPython firmware with following command:
`esptool.py --chip esp32 --port <port> --baud 460800 write_flash -z 0x1000 ESP32_GENERIC-20231005-v1.21.0.bin`

After the procedure finished, open a serial terminal as `minicom` and connect to the board with
`minicom -D <port> -b 115200 -c on`

With the serial console opened, press the reset button and you will see something like
```
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4728
load:0x40078000,len:14876
ho 0 tail 12 room 4
load:0x40080400,len:3368
entry 0x400805cc
MicroPython v1.21.0 on 2023-10-05; Generic ESP32 module with ESP32
Type "help()" for more information.
>>> 
```

Now MicroPython firmware is correctly installed on your ESP32 microcontroller!

To test the correct operation and let the blue led blinking, use the following code:
``` PYTHON
import machine
import time
led = machine.Pin(32, machine.Pin.OUT)
while True:
	led.value(1)
	time.sleep(1)
	led.value(0)
	time.sleep(1)
```

**Comment by ektor5** [comment]
Closing this, thanks @dima91
