### ISSUE TITLE
Failed to get PID of a device on COMx

### ISSUE THREAD

**Issue by letscrypto** [UDOOboard/Key-Docs#4]
I installed esp-idf on Windows 10. The Udoo recommended version 4.4.1 of the generated a not available error from the Git repository so I cloned the default version, which installed successfully. I then built and attempted to flash the blinker program. It failed. 

(NOTE: Udoo "Get Started with ESP32" instruction to install esp-idf v4.4.1 is incorrect.  The actual command should be:
"git clone -b v4.4.1 --recursive https://github.com/espressif/esp-idf.git esp-idf-v4.4.1". If v5.1.1 is installed then blinker.py must be modified to accommodate updated include files)

The error message is "Failed to get PID of a device on com12, using standard reset sequence." I ran esptool.py to troubleshoot the USB serial com connection. The output was:

    C:\Espressif\frameworks\esp-idf-v5.1.1>esptool.py -p com12 flash_id
    esptool.py v4.7.dev1
    Serial port com12
    Connecting...
    Failed to get PID of a device on com12, using standard reset sequence.

    Detecting chip type... Unsupported detection protocol, switching and trying again...
    Connecting...
    Failed to get PID of a device on com12, using standard reset sequence.

    Detecting chip type... ESP32
    Chip is ESP32-D0WD-V3 (revision v3.0)
    Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
    Crystal is 40MHz
    MAC: 8c:4b:14:87:a3:f8
    Stub is already running. No upload is necessary.
    Manufacturer: 20
    Device: 4018
    Detected flash size: 16MB
    Hard resetting via RTS pin...

To me it looks like the USB serial com is communicating with the ESP32 generally but not able to retrieve the PID. I read on several esp-idf forums that the problem is often the Silicon Labs CP210x drivers for Windows. I tried several earlier versions of the drivers, all the way back to 2014, but I got the same result even at reduced baud rates. One posting suggested putting a 1uF capacitor between pin 3 (EN) and GND on the ESP32 to delay CHIP_PU after boot reset. I'm not quite that ambitious or desperate yet.

Anyone had similar problem flashing the ESP32 from esp-idf on Windows or encountering the failed to get PID error message? If so, were you able to resolve it?

###  UPDATE  ###

Installed latest esp-idf v5.1.1 on raspberry pi 4/debian and successfully flashed ESP32 with blinker program and loaded latest RP2040 firmware and MicroPython to successfully run its blinker program as well.  So the Windows problem described above has nothing to do with Udoo Key board; it is definitely a Windows serial I/O problem.

**Comment by dima91** [comment]
Hi @letscrypto 
I just updated the documentation with the ESP-IDF version 5.0.4 and fixing errors on the example code.
I also tested it in Ubuntu 20.04 and Windows 10. If you have another issues, feel free to contact us!
